// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR3XH4vs3gPChZtcW7Td2ZnPtHO5NVcxo',
    appId: '1:35222755716:web:d4c260fc0f37e55a18a5d1',
    messagingSenderId: '35222755716',
    projectId: 'pbl23-70059',
    authDomain: 'pbl23-70059.firebaseapp.com',
    storageBucket: 'pbl23-70059.appspot.com',
    measurementId: 'G-HBS5VT2W7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxM3-PJSAoC8JLcRbAPkoryqMXw3wfpg',
    appId: '1:35222755716:android:ce499242809b668518a5d1',
    messagingSenderId: '35222755716',
    projectId: 'pbl23-70059',
    storageBucket: 'pbl23-70059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClgkg0GnP9MyAQQ6Tw1tt_R-JvDoeJs24',
    appId: '1:35222755716:ios:00fcee00cb4ce37718a5d1',
    messagingSenderId: '35222755716',
    projectId: 'pbl23-70059',
    storageBucket: 'pbl23-70059.appspot.com',
    iosClientId: '35222755716-nlc0377posfdcmc4orjn7b8roa52lfac.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbl',
  );
}
